name: Setup Runner

on:
  push:
    branches: [ "main" ]
    path-ignore:
      - '**/README.md'

  pull_request:
    branches: [ "main" ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          GIT_USER: test
          GIT_EMAIL: test@test.local
        run: |
          cd src
          chmod +x ./setup.sh
          ./setup.sh

  arch:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          GIT_USER: test
          GIT_EMAIL: test@test.local
        run: |
          cd src
          chmod +x ./setup.sh
          ./setup.sh
